// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nrneoqzfeifsqjqsfjsw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ybmVvcXpmZWlmc3FqcXNmanN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MjEyOTgsImV4cCI6MjA2NTI5NzI5OH0.UmljAxvWThtsOw9JiIzytxRPhZEAomSKcd9EuhZ83Uc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);