// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aownmkhmpozozsrhhasq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvd25ta2htcG96b3pzcmhoYXNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MDQ0MDIsImV4cCI6MjA2NTA4MDQwMn0._25e0ZuPUbTB_o4AiJVVd3H37ZFpcZWhiyIYUu2B2zE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);